# Generated by Django 4.1.2 on 2022-10-15 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accomodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Choices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("video", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("rating_room", models.FloatField(default=0)),
                ("rating_house", models.FloatField(default=0)),
                ("rating_bath", models.FloatField(default=0)),
                ("rating_location", models.FloatField(default=0)),
                ("average", models.FloatField(default=0)),
                ("like_count", models.BigIntegerField(default="0")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accom",
                        to="review.accomodation",
                    ),
                ),
                ("choices", models.ManyToManyField(blank=True, to="review.choices")),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="like",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accomodation",
            name="uni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unis",
                to="review.university",
            ),
        ),
    ]
